//MIDI CC control numbers
//These broadly follow standard CC assignments
#define   CCmodwheel  1 //pitch LFO amount - less from mod wheel
#define   CCLfoDepth  3 //pitch LFO amount - panel control
#define   CCvolume 7
#define   CCglide  8
#define   CCosc1_16 9
#define   CCosc1_8 10
#define   CCosc1_32 11
#define   CCosc1_saw 12
#define   CCosc1_tri 13
#define   CCosc1_pulse 14
#define   CCosc1PW 16
#define   CCosc2PW  17
#define   CCosc1PWM  18
#define   CCosc2PWM 19
#define   CClfoTriangle  20
#define   CClfoSquare 21
#define   CCnoiseLevel  23
#define   CCoctave0  24
#define   CCoctave1  25
#define   CCkbOff  26
#define   CCkbHalf  27
#define   CCkbFull  28
#define   CCosc2_16 29
#define   CCsyncOn  30
#define   CCsyncOff  31
#define   CCsingle 32
#define   CCmulti 33
#define   CCosc2_8 36
#define   CCosc2_32 37
#define   CCosc2_saw 38
#define   CCosc2_tri 39
#define   CCosc2_pulse 41
#define   CClfoOscOff 42
#define   CClfoOscOn 43
#define   CCfilterRelease  44
#define   CCfilterAttack 45
#define   CCfilterSustain  46
#define   CCfilterDecay  47
#define   CCfilterlevel  48
#define   CClfoVCFOff 49
#define   CClfoVCFOn 50
#define   CClevel1 51
#define   CClevel2 52
#define   CCbutton1 54
#define   CCbutton2 55
#define   CCbutton3 56
#define   CCbutton4 57
#define   CCbutton5 58
#define   CCbutton6 59
#define   CCbutton7 60
#define   CCbutton8 61
#define   CCbutton9 62
#define   CCbutton10 63
#define   CCbutton11 64
#define   CCPitchBend 65
#define   CCbutton12 66
#define   CCbutton13 67
#define   CCbutton14 68
#define   CCbutton15 69
#define   CCbutton16 70
#define   CCamprelease  72
#define   CCampattack 73
#define   CCfilterCutoff  74
#define   CCampdecay  75
#define   CCLfoRate 77
#define   CCampsustain  79
#define   CCosc2level  81
#define   CCpwLFO  90
#define   CCosc2interval  93
#define   CCfilterRes  94
#define   CCampAttack  95
#define   CCampDecay  96
#define   CCampSustain  97
#define   CCampRelease 98
#define   CCosc1level  103
#define   CCallnotesoff 123//Panic button
